keys:
  - &allison_admin age13cl4dacu3vdw9cttjdys0qrq52q5apz8q9zaa5ax90aruvpqyadqfnphsy
  - &host_authentik age1ghsdwq7j4yfmculja75enwdx93slr2pq8zc9t70fs2vuqa7a432qc68sxc
  - &host_forgejo age1pqvf65525hydme443g5tf4c9ass04pajp6ryjj3xpdal0dsqlepqy4rh95
  - &host_proxy age1usrgz3uuu6mqh3kfzc59g0su6xn4r49s0hptu8nknxegp0j8h46shjkzl7
  - &host_vaultwarden age1vuyq6gcj7j3uzngad4qhghvv7u3ex5gfwvzxplm25ce28gkvjeuqm5p7eh
  - &host_athena age16qq7puuphyk0dzdw7w0yas7se8yv7l35m06yg2gwfwzsr96a3elq5xcu6y
  - &host_artemis age15h3t2n4v7gw47kmurl36mku2eluvua9tpemew76dgx5jj485l3csgrjld2
  - &host_demeter age1tup7frxvvt79mufcec3j97ky5s6eed02xk9re6hkkjzlytuh34fq7rpqjv
  - &host_pythia age1ke28ty7073weu9wl2mwr4mkwkwmjswarcgu06zs7aygkgh9pa4tsd3resu

creation_rules:
  - path_regex: secrets/authentik\.yaml$
    key_groups:
      - age:
          - *allison_admin
          - *host_authentik

  - path_regex: secrets/forgejo\.yaml$
    key_groups:
      - age:
          - *allison_admin
          - *host_forgejo

  - path_regex: secrets/vaultwarden\.yaml$
    key_groups:
      - age:
          - *allison_admin
          - *host_vaultwarden

  - path_regex: secrets/proxy\.yaml$
    key_groups:
      - age:
          - *allison_admin
          - *host_proxy

  - path_regex: secrets/github\.yaml$
    key_groups:
      - age:
          - *allison_admin
          - *host_athena
          - *host_artemis
          - *host_demeter
          - *host_pythia
